### ISSUE TITLE
Volume isn't on even when the icon says it is

### ISSUE THREAD

**Issue by flaw600** [collegiumv/cv_client#27]
It seems that the default for the loud side from what I can tell is to mute the volume until you go into Audio Mixer to fix it via maxing the Front Mic which is mute by default. I logged into a new computer (for me) to prove the point.
![2015-09-09-145447_3200x1080_scrot](https://cloud.githubusercontent.com/assets/9776666/9772973/245f9bc0-5705-11e5-8bb9-d3efcb28ea72.png)

As you can see, even though the volume icon says 100%, the volume is actually muted. It's not hard to fix but most users probably wouldn't know how to.

**Comment by flaw600** [comment]
In case there was any confusion, the quick fix is to turn the Front Mic up, presumably to 100% and then the volume control icon can be used properly. I do not know why the default is to mute the volume, but if I figure that out I will update this.

**Comment by the-maldridge** [comment]
Suspect that programs are not selecting the correct output bus.  Re-test and use pavucontrol to verifiy the program has selected the correct output bus.

**Comment by flaw600** [comment]
You would be correct, from what I can discern. It's not detecting the headphones in pavucontrol. Screenshot is attached. 
![2015-10-19-140501_756x430_scrot](https://cloud.githubusercontent.com/assets/9776666/10588208/93b83b56-766a-11e5-85ef-8fcdb2ebaeab.png)

**Comment by flaw600** [comment]
As for the playback tab, system sounds is turned to silence even with the audio symbol on. So I'm not sure that it's purely a bus problem, as even when I change built in audio to headphones and turn up system sounds it's still muted until I go back into Audio Mixer as per post 1. Another screenshot is attached
![2015-10-19-140837_3200x1080_scrot](https://cloud.githubusercontent.com/assets/9776666/10588342/2ff8c666-766b-11e5-9e42-531b699ce9c7.png)

**Comment by the-maldridge** [comment]
Which machine is this from?  On most of the machines the back and front outputs are electrically joined, but on the machines nearest the windows they are split busses.

**Comment by flaw600** [comment]
Currently on Julin. The first test per post 1 was done on various comps on the social side; I forget the exact machines

**Comment by flaw600** [comment]
Various comps on both sides

**Comment by the-maldridge** [comment]
This issue will be investigated in detail torwards the weekend

**Comment by flaw600** [comment]
Thanks. If you need anymore information from me, let me know. I'm not on campus on the weekends usually but I'll get on any potential request during the nearest work week.

**Comment by the-maldridge** [comment]
Issue cannot be duplicated on a newly generated account on any hardware present.
