### ISSUE TITLE
Install texinfo

### ISSUE THREAD

**Issue by charmoniumQ** [collegiumv/cv_client#39]
AUCTeX (LaTeX package for emacs) requires makeinfo to work. makeinfo is found in the texinfo package.

**Comment by the-maldridge** [comment]
@justanull or @dinoocch   Can you confirm this is necessary?  I seem to remember your emacs working fine without needing additional system packages.

**Comment by JustANull** [comment]
I believe neither of us actually use AUCTeX, we both directly or indirectly just use LaTeX. If AUCTeX requires more packages, neither of us are aware.

**Comment by dinoocch** [comment]
According to the GNU [manual](http://www.gnu.org/software/auctex/manual/auctex/Prerequisites.html#Prerequisites), texinfo is listed as required.  I believe we may fall into the category that it is not, however.

**Comment by dinoocch** [comment]
It should probably be noted that auctex is  (packaged)[https://launchpad.net/ubuntu/trusty/+package/auctex] in Ubuntu...

**Comment by the-maldridge** [comment]
Closed due to innactivity.
