### ISSUE TITLE
Request for f.lux

### ISSUE THREAD

**Issue by rings48** [collegiumv/cv_client#43]
Would be nice

**Comment by the-maldridge** [comment]
This software would duplicate the functionality of redshift, which is already installed.

**Comment by rings48** [comment]
Sounds good. Does it autorun or do I have to run it from terminal? (Didn't see it in the list of programs)
Alex Z.

Date: Fri, 11 Mar 2016 20:09:25 -0800

**Comment by the-maldridge** [comment]
You'll need to configure it for your preferred settings.  This document should help: http://jonls.dk/redshift/

**Comment by rings48** [comment]
Thanks, got it working.
Can you install redshift-gtk ? It gives you an icon then to see if it is running and to control it
AZ

Date: Fri, 11 Mar 2016 20:22:47 -0800
