### ISSUE TITLE
Software Request: nueral-style

### ISSUE THREAD

**Issue by the-maldridge** [collegiumv/cv_client#47]
User request received for https://github.com/jcjohnson/neural-style

**Comment by dinoocch** [comment]
The dependencies for torch have been installed on `ivy`, which is the computer closest to the Archivum.

To install neural-style, you will need to do the following from a terminal:
```bash
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; ./install.sh
```

From there you will need to run:
```bash
luarocks install loadcaffe
```

Finally, you can run the following to get neural-style:
```bash
git clone https://github.com/jcjohnson/neural-style.git
cd neural-style
sh models/download_models.sh
```

We are not installing CUDA or any of the optional dependencies, however, it should work as is from your home folder.

Please note that this will require approximately 157 MB of space.

**Comment by the-maldridge** [comment]
Closed for innactivity.
