### ISSUE TITLE
Cinnamon does not always orient screens correctly

### ISSUE THREAD

**Issue by the-maldridge** [collegiumv/cv_client#52]
Occasionally cinnamon does not load screens with the correct orientation.  This is likely due to the delayed starting of the X server.  The fixScreens script should run with a delay to account for this.

**Comment by m-wynn** [comment]
Is there another hook we can stick fixScreens in?  Maybe a lightdm start hook?

**Comment by the-maldridge** [comment]
It is currently in a hook as the session-setup-script.  The problem is that this runs concurrently with the startup and so we are not assured that it will run after the session X server has started.
