### ISSUE TITLE
Video is choppy on Chrome and Firefox

### ISSUE THREAD

**Issue by flaw600** [collegiumv/cv_client#59]
As the title says, video is choppy on Chrome & FF, both with and w/o hardware acceleration, resulting in screen tear and dropped frames fairly frequently. The specific video sites tested are YouTube and Netflix, with both using HTML5 whenever possible. The computer used to test is Kittens, but I can test on others if need be. I do know that that this wasn't a problem last year, at least on Chrome (I don't use FF), in case that helps. Let me know if there's anything else you need from me.

**Comment by the-maldridge** [comment]
Known issue.

**Comment by flaw600** [comment]
Fair enough, although I wasn't told that when I reported it verbally. Why the won't fix label though @the-maldridge ? It does lead to an unsatisfactory experience watching academic videos, and I presume that the effects get worse the larger the screen (referring to the TV)
