### ISSUE TITLE
Program Request: Eclipse NEON (CDT)

### ISSUE THREAD

**Issue by GiovanH** [collegiumv/cv_client#62]
required for some CS classes

**Comment by the-maldridge** [comment]
4.5.2 is the newest version we can provide at this time.  If you wish to have the latest build we recommend installing it to your home folder.

**Comment by dinoocch** [comment]
Eclipse CDT can be downloaded from [here](http://www.eclipse.org/downloads/eclipse-packages/) and run locally by executing the file `eclipse`.

**Comment by the-maldridge** [comment]
Closed for innactivity
