### ISSUE TITLE
Request: gephi, cytoscape, 

### ISSUE THREAD

**Issue by atbolsh** [collegiumv/cv_client#64]
Useful programs for network analysis and visualization; both have Linux versions, please install.

**Comment by lafrenierejm** [comment]
@atbolsh Is this issue still relevant?

**Comment by the-maldridge** [comment]
Thank you for your interest in the CVOS project.  This repository is no longer actively maintained and is preserved for legacy purposes only.  If your change request is still relevant, please open an issue against the main cv_config repository located at https://github.com/cv_config/
